##################################################
# file: GeocodeService_server.py
#
# skeleton generated by "ZSI.generate.wsdl2dispatch.ServiceModuleWriter"
#      /usr/local/bin/wsdl2py http://dev.virtualearth.net/webservices/v1/geocodeservice/geocodeservice.svc?wsdl
#
##################################################

from ZSI.schema import GED, GTD
from ZSI.TCcompound import ComplexType, Struct
from GeocodeService_types import *
from ZSI.ServiceContainer import ServiceSOAPBinding

# Messages  
IGeocodeService_Geocode_InputMessage = GED("http://dev.virtualearth.net/webservices/v1/geocode/contracts", "Geocode").pyclass

IGeocodeService_Geocode_OutputMessage = GED("http://dev.virtualearth.net/webservices/v1/geocode/contracts", "GeocodeResponse").pyclass

IGeocodeService_ReverseGeocode_InputMessage = GED("http://dev.virtualearth.net/webservices/v1/geocode/contracts", "ReverseGeocode").pyclass

IGeocodeService_ReverseGeocode_OutputMessage = GED("http://dev.virtualearth.net/webservices/v1/geocode/contracts", "ReverseGeocodeResponse").pyclass


# Service Skeletons
class GeocodeService(ServiceSOAPBinding):
    soapAction = {}
    root = {}

    def __init__(self, post='/webservices/v1/geocodeservice/GeocodeService.svc', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_Geocode(self, ps, **kw):
        request = ps.Parse(IGeocodeService_Geocode_InputMessage.typecode)
        return request,IGeocodeService_Geocode_OutputMessage()

    soapAction['http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Geocode'] = 'soap_Geocode'
    root[(IGeocodeService_Geocode_InputMessage.typecode.nspname,IGeocodeService_Geocode_InputMessage.typecode.pname)] = 'soap_Geocode'

    def soap_ReverseGeocode(self, ps, **kw):
        request = ps.Parse(IGeocodeService_ReverseGeocode_InputMessage.typecode)
        return request,IGeocodeService_ReverseGeocode_OutputMessage()

    soapAction['http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/ReverseGeocode'] = 'soap_ReverseGeocode'
    root[(IGeocodeService_ReverseGeocode_InputMessage.typecode.nspname,IGeocodeService_ReverseGeocode_InputMessage.typecode.pname)] = 'soap_ReverseGeocode'

